###
GET http://localhost:1337/api/v1
Content-Type: application/json


###
POST http://localhost:1337/api/v1/product
Content-Type: application/json

{
  "name": "Sp 9",
  "description": "testtt"
}


###
GET http://localhost:1337/api/v1/products
Content-Type: application/json

###
GET http://localhost:1337/api/v1/products/671172f3081a899b1d9a80bf

###
DELETE http://localhost:1337/api/v1/products/671172f3081a899b1d9a80bf